# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - config.yaml
      - COPYING
      - README.md
    name_template: >-
      {{- .ProjectName }}-
      {{- .Tag }}-
      {{- .Os }}-
      {{- .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    
changelog:
  use: github
  format: "{{ .SHA }}: {{ .Message }} ({{ with .AuthorUsername }}@{{ . }}{{ else }}{{ .AuthorName }} <{{ .AuthorEmail }}>{{ end }})"
  # Empty means 'no sorting', it'll use the output of `git log` as is
  sort: ""

checksum:
  split: true

dockers:
  - image_templates:
      - "ghcr.io/ludelafo/panosse:latest-386"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}-386"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}-386"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-386"
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/386"
    extra_files:
      - cmd
      - utils
      - config.yaml
      - go.mod
      - go.sum
      - main.go
  - image_templates:
      - "ghcr.io/ludelafo/panosse:latest-amd64"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}-amd64"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/amd64"
    extra_files:
      - cmd
      - utils
      - config.yaml
      - go.mod
      - go.sum
      - main.go
  - image_templates:
      - "ghcr.io/ludelafo/panosse:latest-armv7"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}-armv7"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}-armv7"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm/v7"
    extra_files:
      - cmd
      - utils
      - config.yaml
      - go.mod
      - go.sum
      - main.go
  - image_templates:
      - "ghcr.io/ludelafo/panosse:latest-arm64"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}-arm64"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"
    extra_files:
      - cmd
      - utils
      - config.yaml
      - go.mod
      - go.sum
      - main.go

docker_manifests:
- name_template: 'ghcr.io/ludelafo/panosse:latest'
  image_templates:
  - 'ghcr.io/ludelafo/panosse:latest-386'
  - 'ghcr.io/ludelafo/panosse:latest-amd64'
  - 'ghcr.io/ludelafo/panosse:latest-armv7'
  - 'ghcr.io/ludelafo/panosse:latest-arm64'
- name_template: 'ghcr.io/ludelafo/panosse:v{{ .Major }}'
  image_templates:
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}-386'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}-amd64'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}-armv7'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}-arm64'
- name_template: 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}'
  image_templates:
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}-386'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}-amd64'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}-armv7'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}-arm64'
- name_template: 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
  image_templates:
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-386'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7'
  - 'ghcr.io/ludelafo/panosse:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64'

release:
  name_template: "{{ .Tag }}"
  header: |
    Release {{ .Tag }} for panosse!

    For usage, configuration and examples, please refer to the project's [README](https://github.com/ludelafo/panosse).
  footer: |
    ## Issues

    If you find any issue, please report it in the project's [Issues](https://github.com/ludelafo/panosse/issues).

    ## Discussions

    For any question, suggestion or discussion, please refer to the project's [Discussions](https://github.com/ludelafo/panosse/discussions).
  mode: replace
  discussion_category_name: General
