## Common

# flac command
flac-command: "flac"

# metaflac command
metaflac-command: "metaflac"

# dry run
dry-run: false

# verbose output
verbose: true

## Clean

# fill missing tags
fill-missing-tags: true

# fill missing tag content
fill-missing-tags-content: "No content for this tag"

# tags to keep
tags-to-keep:
  - "ALBUM"
  - "ALBUMARTIST"
  - "ARTIST"
  - "COMMENT"
  - "DISCNUMBER"
  - "ENCODER_SETTINGS"
  - "GENRE"
  - "REPLAYGAIN_SETTINGS"
  - "REPLAYGAIN_REFERENCE_LOUDNESS"
  - "REPLAYGAIN_ALBUM_GAIN"
  - "REPLAYGAIN_ALBUM_PEAK"
  - "REPLAYGAIN_TRACK_GAIN"
  - "REPLAYGAIN_TRACK_PEAK"
  - "TITLE"
  - "TRACKNUMBER"
  - "TOTALDISCS"
  - "TOTALTRACKS"
  - "YEAR"

# clean arguments
clean-arguments:
  - "--remove"
  - "--dont-use-padding"
  - "--block-type=APPLICATION"
  - "--block-type=CUESHEET"
  - "--block-type=PADDING"
  - "--block-type=PICTURE"
  - "--block-type=SEEKTABLE"

## Encode

# encode if flac versions mismatch between host's flac version and file's flac version
encode-if-flac-versions-mismatch: true

# encode if encode arguments mismatch
encode-if-encode-arguments-mismatch: true

# save encode arguments in tag
save-encode-arguments-in-tag: true

# encode arguments tag name
encode-arguments-tag-name: "FLAC_ARGUMENTS"

# encode arguments
encode-arguments:
  - "--compression-level-8"
  - "--delete-input-file"
  - "--no-padding"
  - "--force"
  - "--verify"
  - "--warnings-as-errors"
  - "--silent"

## Normalize

# ReplayGain arguments
normalize-arguments:
  - "--add-replay-gain"

# normalize arguments tag name
normalize-arguments-tag-name: "REPLAYGAIN_ARGUMENTS"

# normalize if normalize arguments tag is missing
normalize-if-normalize-arguments-tag-is-missing: true

# normalize if ReplayGain tags are missing
normalize-if-replaygain-tags-are-missing: true

# ReplayGain tags
replaygain-tags:
  - "REPLAYGAIN_REFERENCE_LOUDNESS"
  - "REPLAYGAIN_TRACK_GAIN"
  - "REPLAYGAIN_TRACK_PEAK"
  - "REPLAYGAIN_ALBUM_GAIN"
  - "REPLAYGAIN_ALBUM_PEAK"

# save normalize arguments in tag
save-normalize-arguments-in-tag: true

## Verify

# verify arguments
verify-arguments:
  - "--test"
  - "--silent"
