## Common

# Perform a trial run with no changes made
dry-run: false

# flac command (check in $PATH as well)
flac-command: "flac"

# metaflac command (check in $PATH as well)
metaflac-command: "metaflac"

# Enable verbose output
verbose: true

## Clean

# Arguments passed to metaflac to clean the file
clean-arguments:
  - "--remove"
  - "--dont-use-padding"
  - "--block-type=APPLICATION"
  - "--block-type=CUESHEET"
  - "--block-type=PADDING"
  - "--block-type=PICTURE"
  - "--block-type=SEEKTABLE"

# Enable the fill of missing tags
fill-missing-tags: true

# Fill missing tags content
fill-missing-tags-content: "No content for this tag"

# Tags to keep in the file
tags-to-keep:
  - "ALBUM"
  - "ALBUMARTIST"
  - "ARTIST"
  - "COMMENT"
  - "DISCNUMBER"
  - "ENCODER_SETTINGS"
  - "GENRE"
  - "REPLAYGAIN_SETTINGS"
  - "REPLAYGAIN_REFERENCE_LOUDNESS"
  - "REPLAYGAIN_ALBUM_GAIN"
  - "REPLAYGAIN_ALBUM_PEAK"
  - "REPLAYGAIN_TRACK_GAIN"
  - "REPLAYGAIN_TRACK_PEAK"
  - "TITLE"
  - "TRACKNUMBER"
  - "TOTALDISCS"
  - "TOTALTRACKS"
  - "YEAR"

## Encode

# encode arguments
encode-arguments:
  - "--compression-level-8"
  - "--delete-input-file"
  - "--no-padding"
  - "--force"
  - "--verify"
  - "--warnings-as-errors"
  - "--silent"

# encode if encode argument tags mismatch
encode-if-encode-argument-tags-mismatch: true

# encode if flac versions mismatch between host's flac version and file's flac version
encode-if-flac-versions-mismatch: true

# save encode arguments in tag
save-encode-arguments-in-tag: true

# encode arguments tag name
save-encode-arguments-in-tag-name: "FLAC_ARGUMENTS"

## Normalize

# ReplayGain arguments
normalize-arguments:
  - "--add-replay-gain"

# normalize if normalize arguments tags mismatch
normalize-if-normalize-argument-tags-mismatch: true

# normalize if ReplayGain tags are missing
normalize-if-replaygain-tags-are-missing: true

# ReplayGain tags
replaygain-tags:
  - "REPLAYGAIN_REFERENCE_LOUDNESS"
  - "REPLAYGAIN_TRACK_GAIN"
  - "REPLAYGAIN_TRACK_PEAK"
  - "REPLAYGAIN_ALBUM_GAIN"
  - "REPLAYGAIN_ALBUM_PEAK"

# save normalize arguments in tag
save-normalize-arguments-in-tag: true

# normalize arguments tag name
save-normalize-arguments-in-tag-name: "METAFLAC_ARGUMENTS"

## Verify

# verify arguments
verify-arguments:
  - "--test"
  - "--silent"
