## Common

# flac command
flac-command: "flac"

# metaflac command
metaflac-command: "metaflac"

# dry run
dry-run: false

# verbose output
verbose: true

## Clean

# fill missing tags
fill-missing-tags: true

# fill missing tag content
fill-missing-tags-content: "No content for this tag"

# remove application blocks
remove-application-blocks: true

# remove cuesheet blocks
remove-cuesheet-blocks: true

# remove padding blocks
remove-padding-blocks: true

# remove picture blocks
remove-picture-blocks: true

# remove seektable blocks
remove-seektable-blocks: true

# clean settings
clean-settings:
  - "--remove"
  - "--dont-use-padding"
  - "--block-type=APPLICATION"
  - "--block-type=CUESHEET"
  - "--block-type=PADDING"
  - "--block-type=PICTURE"
  - "--block-type=SEEKTABLE"
  - 

# tags to keep
tags-to-keep:
  - "ALBUM"
  - "ALBUMARTIST"
  - "ARTIST"
  - "COMMENT"
  - "DISCNUMBER"
  - "ENCODER_SETTINGS"
  - "GENRE"
  - "REPLAYGAIN_SETTINGS"
  - "REPLAYGAIN_REFERENCE_LOUDNESS"
  - "REPLAYGAIN_ALBUM_GAIN"
  - "REPLAYGAIN_ALBUM_PEAK"
  - "REPLAYGAIN_TRACK_GAIN"
  - "REPLAYGAIN_TRACK_PEAK"
  - "TITLE"
  - "TRACKNUMBER"
  - "TOTALDISCS"
  - "TOTALTRACKS"
  - "YEAR"

## Encode

# encode if flac versions mismatch between host's flac version and file's flac version
encode-if-flac-versions-mismatch: true

# encode if encode settings mismatch
encode-if-encode-settings-mismatch: true

# save encode settings in tag
save-encode-settings-in-tag: true

# encode settings tag name
encode-settings-tag-name: "FLAC_SETTINGS"

# encode settings
encode-settings:
  - "--compression-level-8"
  - "--delete-input-file"
  - "--no-padding"
  - "--force"
  - "--verify"
  - "--warnings-as-errors"
  - "--silent"

## Normalize

# normalize if normalize command arguments tag is missing
normalize-if-normalize-command-arguments-tag-is-missing: true

# save normalize command arguments in tag
save-normalize-command-arguments-in-tag: true

# normalize command arguments tag name
normalize-command-arguments-tag-name: "REPLAYGAIN_SETTINGS"

# ReplayGain settings
normalize-command-arguments:
  - "--add-replay-gain"

# normalize if ReplayGain tags are missing
normalize-if-replaygain-tags-are-missing: true

# ReplayGain tags
replaygain-tags:
  - "REPLAYGAIN_REFERENCE_LOUDNESS"
  - "REPLAYGAIN_TRACK_GAIN"
  - "REPLAYGAIN_TRACK_PEAK"
  - "REPLAYGAIN_ALBUM_GAIN"
  - "REPLAYGAIN_ALBUM_PEAK"

## Verify

# verify settings
verify-command-arguments:
  - "--test"
  - "--silent"
